steps:
#Perform the terrafrom plan 
  - name: 'hashicorp/terraform:1.0.0'
    id: terraform-plan
    dir: ${_DIR}/${_TF_DIR}
    entrypoint: sh
    args: 
    - '-c' # pass what follows as a command to bash
    - |
      terraform init -backend-config="${_BACKEND_CONFIG_BUCKET}" -backend-config="${_BACKEND_CONFIG_PREFIX}"
      terraform ${_TF_COMMAND} -var-file=${_VAR_FILE}
    env:
      - "TF_VAR_project-name=${PROJECT_ID}"
      - "TF_LOG=${_TF_LOG}" 
    volumes:
    - name: 'ssh'
      path: /root/.ssh

substitutions:
    _KEY_PROJECT: fabled-variety-403701
    _KEY_VERSION: "latest"
    _GIT_P_KEY: gkey
    _REGISTRY_PROJECT: fabled-variety-403701
    _TERRAFORM_VERSION: terraform:0.14.9
    _DIR: .
    _TF_COMMAND: plan
    _TF_DIR: terraform
    _BACKEND_CONFIG_BUCKET: bucket=${PROJECT_ID}-tfstate
    _BACKEND_CONFIG_PREFIX: prefix=terraform/np
    _VAR_FILE: np.tfvars
    _TF_LOG:
